### PR TITLE
add pilgrimage theme styles

### LINKED ISSUE #134: Variation: Pilgrimage
grafik

grafik

grafik

Figma: https://www.figma.com/file/0NcNCYScCtXrgbUQ6Z6fAf/TT3%3A-Pilgrimage

### PR DESCRIPTION
**Pull request by kathryncodes**
addresses #134 

Please let me know if any changes are needed and I will be sure to get them in the next couple days. Thanks!

### CODE REVIEW

**Comment by madhusudhand** [comment]
@kathryncodes A style variation doesn't need to duplicate all styles from main `theme.json` because they are combined to produce final results. Include the style definitions that are different from the main theme.json. 
As an example, `color palette`, `core-navigation -> elements -> color` etc.. are the changes this variation can have.

Here is a similar variation definition #157 for your reference.

**Comment by kathryncodes** [comment]
@madhusudhand ah okay, I was actually trying to referencing that file but I suppose I didn't need to include everything in it. This file is what I got from using the block theme plugin on my local environment, but I can trim it down. Would your suggestion be to simply remove any code that's the same as theme.json?

**Comment by carolinan** [comment]
> Would your suggestion be to simply remove any code that's the same as theme.json?

Yes

**Comment by kathryncodes** [comment]
Latest commit has all the duplicate theme.json styles removed from pilgrimage.json

@carolinan @madhusudhand thank you for being so helpful!

**Comment by mikachan** [comment]
Thanks for working on this! ❤️ It's looking great. I've just pushed a few commits to fix up some formatting, colours and to add the variation title. I've also added a subtle background gradient as mentioned in [this comment](https://github.com/WordPress/twentytwentythree/issues/134#issuecomment-1239673196).

**Comment by beafialho** [comment]
I'm not seeing the intended duotone in the images: 

Captura de ecrã 2022-09-19, às 10 43 11

**Comment by mikachan** [comment]
> I'm not seeing the intended duotone in the images:

Oh, good spot! It looks like we were missing the duotone filter. I've added this and applied it to all images.

**Comment by madhusudhand** [comment]
Also, should the background be gradient? I refer single color background `base` from figma.

**Comment by mikachan** [comment]
> Also, should the background be gradient? I refer single color background base from figma.

This was requested in [this comment here](https://github.com/WordPress/twentytwentythree/issues/134#issuecomment-1239673196), but it would be great to know if this was the intended effect!

**Review by mikachan — APPROVED** [review]
In order to include this variation in Beta 1, I'm going to merge this now. Please feel free to open any additional PRs to make any changes!

**Pull request merged**
