### PR TITLE
Add alternative-blog.html

### PR DESCRIPTION
**Pull request by carolinan**
Adds the alternative blog template from the design.

### CODE REVIEW

**Review by mikachan — COMMENTED** [review]
Thanks for this, it looks good to me ✨

**Comment by beafialho** [comment]
~~This isn't looking like the designs for me: it's missing the separators, the post date isn't with the same format and letter case.~~

My bad, I wasn't testing correctly. My only comment is that the query loop should be wide instead.

**Comment by carolinan** [comment]
I will change it to wide.

-What do you think the name of the file and the visual label in the editor should be?

Assuming this should be selectable in the drop down for pages, for example when the "Front page displays..." setting is used to select a separate page for the blog.

**Comment by beafialho** [comment]
> -What do you think the name of the file and the visual label in the editor should be?

I think it could be **Blog (Alternative)**.

**Review by mikachan — APPROVED** [review]

**Pull request merged**
