### PR TITLE
Add hover state to Query Pagination and Post Date links

### PR DESCRIPTION
**Pull request by mikachan**
This updates the hover state of the links in Query Pagination and Post Date blocks.

Also tested that the pseudo-state styles work with Query Pagination numbers.

Part of https://github.com/WordPress/twentytwentythree/issues/182.

### CODE REVIEW

**Review by madhusudhand — APPROVED** [review]
The changes looks good.

I have a question. In comments, edit and reply links are in opposite states like 
edit: no-underline (default) and underline (hover)
reply: opposite

Shouldn't they both behave same? I guess "edit" link states are wrong.

**Comment by carolinan** [comment]
I believe Bea made a list of all the different hover states, I'll try to see if I can find it.

**Comment by mikachan** [comment]
Ah, I probably set the styles the wrong way around?  I'll check them against the designs [here](https://www.figma.com/file/ohYEHkZzGjOse46NceTfj5/Twenty-Twenty-Three?node-id=301%3A761).

**Comment by mikachan** [comment]
Thanks both, all the links in the comments should now be consistent.

**Review by carolinan — APPROVED** [review]

**Pull request merged**
