### PR TITLE
Fix typo in home.html

### LINKED ISSUE #102: Home.html: Typo in Heading
I believe there is a typo here: https://github.com/WordPress/twentytwentythree/blob/trunk/templates/home.html#L19

```
<h3 class="has-small-font-size" style="font-style:normal;font-weight:400;text-transform:uppercase">Latests posts</h3>
```

Should be:

```
<h3 class="has-small-font-size" style="font-style:normal;font-weight:400;text-transform:uppercase">Latest posts</h3>
```

### PR DESCRIPTION
**Pull request by bgardner**
Fixes #102

### CODE REVIEW

**Comment by carolinan** [comment]
This whole section is being removed: https://github.com/WordPress/twentytwentythree/issues/43#issuecomment-1223677701

**Review by madhusudhand — APPROVED** [review]
LGTM!

**Comment by mikachan** [comment]
There's now a PR to remove this section from the home template: https://github.com/WordPress/twentytwentythree/pull/111

**Comment by bgardner** [comment]
Should I just cancel this PR then?

**Pull request closed without merging**
