### PR TITLE
Consolidate single templates

### LINKED ISSUE #133: Use Cover block instead of Post Featured Image to enhance designs
I've worked on a design in Figma with the provided template, before actually looking at the code. I noticed that for the queries and templates, the Post Featured Image block is used to display images. In my design, I thought of giving the images a gradient overlay like you can do with the Cover block. But with the current setup, this design is not possible.

So I want to kick of a discussion of changing the Post Featured Images to Cover blocks, to enable a wider varierty of designs. Any thoughts?

Here's a preview of my design:
grafik

I also saw that @critterverse has been working on a design using duotones but the images don't really display well there. I think with using a gradient, it would be much more pleasing to the eye: https://github.com/WordPress/twentytwentythree/issues/125

### LINKED ISSUE #178: Post meta pattern in Page types
By default, when creating a page (`page.html`), the page does not display a post meta (with information about date, author, tags) section under the content. 

And I guess it's good because post meta section is more relevant to Post types rather than Page types.

However, when changing template to a page with featured image (`with-featured-image.html`), or to a page with cover block (`with-cover-block.html`), the page displays the post meta section under the content.

I am wondering if it's done intentionally, or is it a bug?

Page with default template:

page-with-default-template

Page with featured image template:

page-with-featured-image-template

### PR DESCRIPTION
**Pull request by mikachan**
Now that https://github.com/WordPress/gutenberg/issues/43676 has been merged, I believe we can consolidate the single templates as discussed [here](https://github.com/WordPress/twentytwentythree/issues/133).

Should we include the featured image on the page template as well?

### CODE REVIEW

**Comment by beafialho** [comment]
Yes, let's include the featured image on the page template as well as in the [mockup](https://www.figma.com/file/ohYEHkZzGjOse46NceTfj5/Twenty-Twenty-Three?node-id=301%3A514).

**Review by madhusudhand — COMMENTED** [review]
Looks good.

Following are few minor queries.

Not sure if the space between the image and header is accurate. @beafialho could you confirm.
image

Canary has the issue with corner adjustment: (top left)
image

**Comment by mikachan** [comment]
Thanks for taking a look @madhusudhand!

> Canary has the issue with corner adjustment: (top left)

Good spot, seems like the border radius needs to be applied to the featured image overlay in GB. It looks like the cover block has the same issue. I believe GB 14.1 is the latest version that's going to be included in WP 6.1, so I'm not sure we can include a fix as part of the release. I've opened an issue for this here: https://github.com/WordPress/gutenberg/issues/44262

Should we stick with the 3 separate templates for now?

**Comment by mikachan** [comment]
https://github.com/WordPress/gutenberg/pull/44286 / https://github.com/WordPress/gutenberg/pull/44276 should unblock this 🎉

**Comment by mikachan** [comment]
As https://github.com/WordPress/gutenberg/pull/44286 is [confirmed](https://wordpress.slack.com/archives/C02QB2JS7/p1664818529934669?thread_ts=1664812732.303779&cid=C02QB2JS7) as being included in 6.1 Beta 3, I'm going to merge this so we can test these changes together as part of Beta 3.

**Pull request merged**
