### PR TITLE
Variation: Grapes

### LINKED ISSUE #126: Variation: "Grapes"
image

imageimage
image

Figma: https://www.figma.com/file/8XBx2sZ6GYYQmdOeOp0tAf/Variation-Grapes?node-id=1%3A164
Variation JSON: [grapes.zip](https://github.com/WordPress/twentytwentythree/files/9437023/grapes.zip)

### PR DESCRIPTION
**Pull request by WBerredo**
### Patterns

---

Fixes #126

### CODE REVIEW

**Comment by WBerredo** [comment]
> We’ve replaced one of the two green colors for black because they were so similar to each other.

I would like to clarify two points:
- Which one of the green colors should we replace for black? The primary or secondary?
- For black, you mean `#000000`?w

**Comment by WBerredo** [comment]
> Which one of the green colors should we replace for black? The primary or secondary?

Considering the following image, I assume the secondary color should be replaced to black.
The change can be found at https://github.com/WordPress/twentytwentythree/pull/157/commits/2db206338bd0e27cd00d836d31cfd1ca3192947f

Screen Shot 2022-09-11 at 14 35 56

**Review by mikachan — APPROVED** [review]
Thanks for working on this! ❤️ This is looking great to me.

> Considering the following image, I assume the secondary color should be replaced to black.

I believe this is correct. @beafialho, could you please confirm?

**Comment by beafialho** [comment]
That is correct, these look good to me!

**Pull request merged**
